name: Build And Test

on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches:
      - master
      - release/*

env:
  BUILD_TYPE: Release

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          echo "Installing ninja..."
          sudo apt-get install \
              ninja-build      \
          ; echo "Done!"
          
          echo "Installing libgl..."
          sudo apt-get install \
              libgl-dev        \
          ; echo "Done!"

          echo "Installing glfw dependencies..."
          sudo apt-get install \
              libxrandr-dev    \
              libxinerama-dev  \
              libx11-dev       \
              libxcursor-dev   \
              libxi-dev        \
          ; echo "Done!"

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -G Ninja

      - name: Build
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: cmake --build . --config $BUILD_TYPE

      - name: Test
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: ctest -C $BUILD_TYPE --output-on-failure
